version: '2'
services:
  svelte-test:
    build:
      context: ./
    container_name: svelte-test
    hostname: svelte-test
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    command: >
      ash -c "npm install;
      npm run dev;
      tail -f /dev/null"
    ports:
      - 80:3000
      - 24678:24678
    environment:
      - NODE_ENV=development

